version: "3.3"
services:
  app:
    build:
      args:
        user: zope
        path: /zope/
        userZope: 
        passZope: 
        portZope: 8080
      context: ./
      dockerfile: Dockerfile
    tty: true
    image: assine-bem-demonstracao-img
    container_name: assine-bem-demonstracao-app
    restart: unless-stopped
    ports:
      - "8099:8080"
